CREATE TABLE games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(100) NOT NULL,
    title VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT games_pkey PRIMARY KEY (id),
    CONSTRAINT games_code_key UNIQUE (code)
);

CREATE TABLE game_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    game_id BIGINT NOT NULL,
    code VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT game_keys_pkey PRIMARY KEY (id),
    CONSTRAINT game_keys_code_key UNIQUE (code),
    CONSTRAINT game_keys_game_id_fkey FOREIGN KEY (game_id) REFERENCES games (id)
);

CREATE TABLE allocations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    game_key_id BIGINT NOT NULL,
    allocated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT allocations_pkey PRIMARY KEY (id),
    CONSTRAINT allocations_game_key_id_key UNIQUE (game_key_id),
    CONSTRAINT allocations_game_key_id_fkey FOREIGN KEY (game_key_id) REFERENCES game_keys (id)
);

CREATE TABLE idempotency_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    idempotency_key VARCHAR(255) NOT NULL,
    allocation_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT idempotency_records_pkey PRIMARY KEY (id),
    CONSTRAINT idempotency_records_idempotency_key_key UNIQUE (idempotency_key),
    CONSTRAINT idempotency_records_allocation_id_key UNIQUE (allocation_id),
    CONSTRAINT idempotency_records_allocation_id_fkey FOREIGN KEY (allocation_id) REFERENCES allocations (id)
);
