CREATE TABLE authentication_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT authentication_identities_pkey PRIMARY KEY (id),
    CONSTRAINT authentication_identities_username_key UNIQUE (username)
);
